### ISSUE TITLE
Module does not expose any code and other strange bugs.

### ISSUE THREAD

**Issue by chrstntdd** [ccapndave/fuse-box-elm-plugin#1]
First off let me say that I am so excited that you made this plugin. I've been settling with Webpack and had plans to do something like this myself, but couldn't find the time. 

That being said, I am having a few issues with this so far. For starters, the module on npm `v1.0.1` does not expose any code.
![image](https://user-images.githubusercontent.com/17863654/33236696-8a9487e2-d229-11e7-9beb-b013620b749d.png)

This is a small issue, but I cloned the repo, compiled `index.ts` to an appropriate `.js` file and attempted to use the module in an existing elm project I have. Running the plugin wouldn't compile my Elm code at all, and after adding the line below, I was able to get a bit more info about the error: 
```
proc.on('error', err => { console.log(err); });
```
err is:

```
{ Error: spawn T:\Development\projects\elm\merch-tool\node_modules\.bin\elm-make ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn T:\\Development\\projects\\elm\\merch-tool\\node_modules\\.bin\\elm-make',
  path: 'T:\\Development\\projects\\elm\\merch-tool\\node_modules\\.bin\\elm-make',
  spawnargs:
   [ '--yes',
     '--output',
     'C:\\Users\\CHRIST~1\\AppData\\Local\\Temp\\tmp-34161qR51wezu1yV.js',
     '--warn',
     '--debug',
     'T:\\Development\\projects\\elm\\merch-tool\\src\\client\\Main.elm' ] }
```

I have installed and then reinstalled elm globally via npm, and the `.bin` file exists at the path listed in the error output. I apologize for the strange paths as I was using this plugin on my Windows 10 machine. I will give this a try on my Mac to see if there are any differences.

---

Finally, as I was logging out the errors, I'm noticing that the output was always doubled. In fact, it seemed that every method on the class would be called twice. Not too sure about this one, but I figured I would mention it.

**Comment by ccapndave** [comment]
Thanks a lot for the comments! Full disclosure - I've never tested it on Windows so there is every possibility that it doesn't work at the moment.

I'll sort out the embarassing npm deployment issue asap (that's what happens when you rush releasing something).

Strange about the double outputs; I wonder if it's because the process is redirecting to stdio, so it's getting printed once with the listener and then again on stderr.

**Comment by chrstntdd** [comment]
<img width="763" alt="screen shot 2017-11-26 at 9 45 31 am" src="https://user-images.githubusercontent.com/17863654/33241063-a2735a2c-d28e-11e7-8d87-6bddf1f24a7b.png">

Alright, so I pulled in `v1.0.2` and with no config options, the bundling still runs twice for some reason, note the distinct temporary filenames in the terminal output. I have switched over to my Macbook to test this out and I'm hitting a few snags. It seems `elm-make` is running properly, no errors (I don't think I configured my windows machine to have access to the `elm-make` command), but the output files only include the elm runtime and none of my Elm code. I have required `Main.elm` within my entry point file `index.js`, but I still can't get the expected outcome. I hope I've been detailed enough with what my setup is looking like thus far. 

###  * *UPDATE* *
This is embarrassing, I actually injected `ElmPlugin()` in my css plugin array and that was causing the bundling error where none of my `.elm` files were being compiled. Missed it by a single bracket. All is well now! Thank you so much for this plugin. I can finally shed Webpack once and for all 😁

**Comment by chrstntdd** [comment]
This particular issue has been addressed, so for now I'll close this. Additionally, I believe that the two output files may be in relation to the two `.elm` files within this particular project. I cannot thank you again for the work you've put in here 👍

**Comment by chrstntdd** [comment]
This particular issue has been addressed, so for now I'll close this. Additionally, I believe that the two output files may be in relation to the two `.elm` files within this particular project. I cannot thank you again for the work you've put in here 👍
